# Generated by Django 4.1.5 on 2023-01-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerModel',
            fields=[
                ('empid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('experience', models.PositiveIntegerField()),
                ('date_of_join', models.DateField()),
                ('salary', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
